### ISSUE TITLE
HomeBridge blog post

### ISSUE THREAD

**Issue by balloob** [balloob/home-assistant.io#87]
@maddox added support for Home Assistant to HomeBridge. We need a blog post to educate people of this feature.

We can start the blog post with a link to the [HomeBridge getting started guide](https://github.com/nfarina/homebridge#getting-started). They know better how to set it up then we ever will.

Next we should include a Home Assistant config (@maddox?, @CCOSTAN?).

If I recall correctly, @maddox added support for showing certain devices as switches/lights in Siri. Anyone has more info on this and how can it be used with HomeBridge?

We might want to include a cool example how to use Siri to use a command line switch to execute commands?

**Comment by maddox** [comment]
I'll work on a first draft of this tonight. My plan is to split this up into 2 posts. The first, introducing homebridge and how to set it up. And the second, how to really tweak and get the best out of it.

> If I recall correctly, @maddox added support for showing certain devices as switches/lights in Siri

I made it so you could [white list which of your device types showed up](https://github.com/nfarina/homebridge/blob/master/platforms/HomeAssistant.js#L63).

> We might want to include a cool example how to use Siri to use a command line switch to execute commands

I'm hesitant to suggest this unless it's natural to use the word "on" or "off" for this switch, since that's the only actionable verb Siri really understands right now. 

I.E, 

I DO think it's great to bridge a command switch that turns your tv on/off via a command switch that CURLs a URL. -> `siri, turn on the TV`.

I DO NOT think it's ok to bridge a command switch that just does some arbitrary command. Sure, it's doable, but it's pretty hacky and gross.

**Comment by maddox** [comment]
My HomeKit setup has completely :hankey: the bed. I'm going to have to figure out what's going on with it before suggesting it to others :)

It's so weird. It's acting like it doesn't know what any of my devices are. I'll get to the bottom of it.

**Comment by balloob** [comment]
Could it be compatibility issues between El Capitain and HomeBridge ?

**Comment by maddox** [comment]
It actually looks like Siri might have screwed stuff up. Even though I reset my HomeKit DB/configuration, it was still messed up. 

After doing it a few more times and dealing with another issue, I was able to get things working fine again.

**Comment by CCOSTAN** [comment]
I find that Siri loses DB access on various devices and accessories seem to lose their room configuration all the time.
Check out my virtualization blog at www.vCloudInfo.com<http://www.vcloudinfo.com/>!
Follow me : Twitter: @ccostan<http://www.twitter.com/ccostan> | FaceBook <http://www.facebook.com/VMwareInfo>

**Comment by frekel** [comment]
@maddox: Is this in any release yet?

If so, Do you need testers?
If not, How can I include it in my setup? And --> see If so ;)

**Comment by maddox** [comment]
@frekel This is already available. You just need to set up [Homebridge](https://github.com/nfarina/homebridge) and set it up to read from your HA installation. 

Home bridge's README has everything you need to know to set it up. You can read about setting up Home Assistant integration in the [head of it's integration file](https://github.com/nfarina/homebridge/blob/master/platforms/HomeAssistant.js#L1).

**Comment by frekel** [comment]
@maddox: Thanks for the info.

I just tried to install it, but if fails... hopefully I have some spare time between the Halloween festivals ;)

**Comment by balloob** [comment]
It looks like Homebridge has split out all plugins into separate packages. Home Assistant is currently available in the legacy plugin package.

**Comment by balloob** [comment]
Closing this as we had it mentioned in community highlights.
